# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - check-content

on:
  push:
    branches:
      - master
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache transformers models
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/huggingface/transformers
          key: ${{ runner.os }}-transformers-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-transformers-

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Here you can add steps to run tests or other build tasks

      - name: Deploy updated Python files to Azure Web App
        run: |
          az webapp up --name check-content --src-path 
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_646CF6C9B3CE4949AB7DE159BA3AECAC }}